#!/bin/bash

# Quick setup script for Blog Promotion Agent

echo "==================================="
echo "Blog Promotion Agent Setup"
echo "==================================="
echo ""

# Check if .env exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists."
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env file."
    else
        rm .env
    fi
fi

# Create .env if it doesn't exist
if [ ! -f ".env" ]; then
    echo "Creating .env file..."
    
    # Get Substack URL
    echo ""
    echo "📝 Enter your Substack URL (e.g., yourname.substack.com):"
    read -p "Substack URL: " substack_domain
    
    # Construct RSS feed URL
    if [[ $substack_domain == http* ]]; then
        substack_url="${substack_domain}/feed"
    else
        substack_url="https://${substack_domain}/feed"
    fi
    
    # Get API key
    echo ""
    echo "🔑 Enter your Anthropic API key:"
    echo "   Get one at: https://console.anthropic.com/"
    read -p "API Key: " api_key
    
    # Optional: Check interval
    echo ""
    echo "⏱️  How often should the agent check for new posts? (minutes)"
    read -p "Check interval [60]: " check_interval
    check_interval=${check_interval:-60}
    
    # Write .env file
    cat > .env << EOF
# Environment Configuration
# Generated by setup script

# Your Substack RSS feed URL
SUBSTACK_URL=$substack_url

# Anthropic API Key
ANTHROPIC_API_KEY=$api_key

# Check interval in minutes
CHECK_INTERVAL_MINUTES=$check_interval
EOF
    
    echo ""
    echo "✅ .env file created successfully!"
fi

echo ""
echo "==================================="
echo "Setup Complete!"
echo "==================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Start the agent:"
echo "   docker-compose up -d"
echo ""
echo "2. Access the dashboard:"
echo "   http://localhost:5000"
echo ""
echo "3. Check logs:"
echo "   docker-compose logs -f"
echo ""
echo "For more information, see README.md"
echo ""
