# Blog Promotion Agent Setup Script (PowerShell)
# Run this script to configure your environment

Write-Host "===================================" -ForegroundColor Cyan
Write-Host "Blog Promotion Agent Setup" -ForegroundColor Cyan
Write-Host "===================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env exists
if (Test-Path ".env") {
    Write-Host "⚠️  .env file already exists." -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Keeping existing .env file." -ForegroundColor Green
        $skipEnv = $true
    } else {
        Remove-Item ".env"
        $skipEnv = $false
    }
} else {
    $skipEnv = $false
}

# Create .env if needed
if (-not $skipEnv) {
    Write-Host "Creating .env file..." -ForegroundColor Green
    
    # Get Substack URL
    Write-Host ""
    Write-Host "📝 Enter your Substack URL (e.g., yourname.substack.com):" -ForegroundColor Yellow
    $substackDomain = Read-Host "Substack URL"
    
    # Construct RSS feed URL
    if ($substackDomain -match "^https?://") {
        $substackUrl = "$substackDomain/feed"
    } else {
        $substackUrl = "https://$substackDomain/feed"
    }
    
    # Get API key
    Write-Host ""
    Write-Host "🔑 Enter your Anthropic API key:" -ForegroundColor Yellow
    Write-Host "   Get one at: https://console.anthropic.com/" -ForegroundColor Gray
    $apiKey = Read-Host "API Key"
    
    # Optional: Check interval
    Write-Host ""
    Write-Host "⏱️  How often should the agent check for new posts? (minutes)" -ForegroundColor Yellow
    $checkInterval = Read-Host "Check interval [60]"
    if ([string]::IsNullOrWhiteSpace($checkInterval)) {
        $checkInterval = "60"
    }
    
    # Write .env file
    $envContent = @"
# Environment Configuration
# Generated by setup script

# Your Substack RSS feed URL
SUBSTACK_URL=$substackUrl

# Anthropic API Key
ANTHROPIC_API_KEY=$apiKey

# Check interval in minutes
CHECK_INTERVAL_MINUTES=$checkInterval
"@
    
    $envContent | Out-File -FilePath ".env" -Encoding UTF8
    
    Write-Host ""
    Write-Host "✅ .env file created successfully!" -ForegroundColor Green
}

Write-Host ""
Write-Host "===================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Cyan
Write-Host "===================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Start the agent:" -ForegroundColor White
Write-Host "   docker-compose up -d" -ForegroundColor Gray
Write-Host ""
Write-Host "2. Access the dashboard:" -ForegroundColor White
Write-Host "   http://localhost:5000" -ForegroundColor Gray
Write-Host ""
Write-Host "3. Check logs:" -ForegroundColor White
Write-Host "   docker-compose logs -f" -ForegroundColor Gray
Write-Host ""
Write-Host "For more information, see README.md" -ForegroundColor Yellow
Write-Host ""
