[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:agent]
command=python agent.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/agent.err.log
stdout_logfile=/var/log/supervisor/agent.out.log

[program:server]
command=python server.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/server.err.log
stdout_logfile=/var/log/supervisor/server.out.log
